version: '3'

services:
  broker:
    # build:
      # context: .
      # dockerfile: Dockerfile
    image: signetframework/signet-broker:latest
    container_name: signet-broker
    deploy:
      restart_policy:
        condition: on-failure
    restart: unless-stopped
    depends_on:
      - db
    # env_file: .env
    environment:
      - PORT=3001
      - NODE_ENV=production
      - RDS_USERNAME=postgres
      - RDS_HOSTNAME=db
      - RDS_DB_NAME=postgres
      - RDS_PASSWORD=browni3s
      # - RDS_PORT=5432
      # - ENABLE_DB_SSL=true
    ports:
      - "3001:3001"
    # volumes:
      # - .:/home/node/app
      # - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    working_dir: /home/node/app
    command: ./wait-for.sh db:5432 -t 500 -- npm start
    # command: /home/node/app/node_modules/.bin/nodemon src/app.js
  db:
    image: signetframework/signet-db:latest
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
    container_name: db
    # env_file: .env
    # environment:
      # - POSTGRES_PASSWORD=
      # - POSTGRES_DB=postgres
    volumes:
      - dbdata:/data/db
      # - ./src/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
